### ISSUE TITLE
Any sample geojson

### ISSUE THREAD

**Issue by am2222** [kothic/kothic-node#1]
Hi,
I guess the geojson format which is used in this library is different since I see in source that library reads `geojson.box` parameter. Is there any example of geojson which I can use it?
thanks

**Comment by Miroff** [comment]
'bbox' parameter is introduced as an optional parameter in [RFC7946](https://tools.ietf.org/html/rfc7946#section-5)

I'm going to make this parameter optional in Kothic, but it is really needed for viewport calculation. Anyway, here is a [sample GeoJSON file](https://gist.github.com/Miroff/2a11e82de0ecbb19ff5bb1f00fd3eb6e)

**Comment by am2222** [comment]
@Miroff Thanks
By the way which coordinate system is your geojson data? I guess it is nighter EPSG:3857 nor EPSG:4326

**Comment by Miroff** [comment]
@am2222 it's in ESPG:3857

**Comment by am2222** [comment]
@Miroff Thanks so much, so I believe it is much easier to use this nodejs version than the original one, since the original one needed to have tiles in an specific format.

**Comment by am2222** [comment]
@Miroff 
Hi,
I am trying to render the following geojson using this library but it does not render anything. Can you help me to find my mistake??

```
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "way": "highway"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -15396748.037696483,
              10357735.672382466
            ],
            [
              -16414963.077749506,
              8745321.856230162
            ],
            [
              -15607668.782728348,
              7226856.416992388
            ],
            [
              -14256462.355032187,
              6980670.536077075
            ],
            [
              -13017668.705772694,
              8016978.428844904
            ],
            [
              -13178236.930036379,
              9743709.268002428
            ],
            [
              -15396748.037696483,
              10357735.672382466
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "way": "highway"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -11149509.006536502,
              10721554.157796513
            ],
            [
              -13178236.930036379,
              9743709.268002428
            ],
            [
              -13017668.705772694,
              8016978.428844904
            ],
            [
              -11637632.51812718,
              7267145.63540028
            ],
            [
              -10120333.817887489,
              7675849.707050307
            ],
            [
              -9559961.715910625,
              9189786.607854018
            ],
            [
              -11149509.006536502,
              10721554.157796513
            ]
          ]
        ]
      }
    }
  ],
  "bbox": [
    -20037508.342789244,
    -20037508.342780847,
    0,
    -5.52330055025865e-8
  ]
}

```

I am using this functions

```

		const css = "way[way] { width: 1; color: red;}";
		const kothic = new Kothic(css, {
			//Synchronous mode for testing reasons
			getFrame: (callback1) => callback(),
			browserOptimizations: false,
			gallery: {
				localImagesDirectory: '../../sandbox/maki/png',
				loadImage: function (image) {
					return undefined;
				}
			},
			mapcss: {
				cache: {},
				locales: []
			},
			debug: true
		});

		kothic.render(
			canvas, // canvas element (or its id) to render on
			newdata.features, // GeoJSON data to render
			this.z + configuration.zoomOffset, // zoom level
			function () {
				self.debug('Finished rendering bitmap tile.');
				return process.nextTick(function () {
					callback(false, canvas);
				});
			} // onRenderingComplete callback
		);
		var buf = canvas.toBuffer();
		fs.writeFileSync("F:\\test.png", buf);

```

**Comment by Miroff** [comment]
1. The bbox in your GeoJSON doesn't match to the features. Both features lays outside the bbox, therefore will not be visible.
2. Kothic.render function takes GeoJSON as an argument, not a features list.
3. You must save rendering result in a Kothic.render callback, due to a JS asynchronous nature. 

[Here](https://gist.github.com/Miroff/83b1ae691a8b960004b361f41660f8b0) I changed your example to show something, hope it will help.

**Comment by am2222** [comment]
@Miroff Wow, thanks so much. it works great. Now I can easily render my results. 
However I have two questions, first whether if I can change 
``
const canvas = createCanvas(512* 4, 512 *4)
``
to `256*256` tiles size? does it have any impact on my output? and also I had a question about styling method. I know that its not a kind of styling which is being supported in most of map renderings which render osm data. But suppose we have a property named value which is a numeric parameter. Is it to set style in a such way to get fill color from a function based on that field?suppose we know min, max.
